# Generated by Django 4.2.6 on 2023-11-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credit_limit', models.IntegerField(default=0)),
                ('current_outstanding', models.IntegerField(default=0)),
                ('utilization_ratio', models.FloatField()),
                ('new_application', models.BooleanField(default=True)),
                ('loan_type', models.CharField(choices=[('Auto Loan', 'Auto Loan'), ('Mortgage Loan', 'Mortgage Loan'), ('Other', 'Other')], default='Other', max_length=250)),
                ('emi_payment', models.BooleanField()),
                ('past_due_days', models.CharField(choices=[('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], max_length=50)),
                ('pay_emi_next_month', models.BooleanField()),
                ('settlement', models.BooleanField()),
                ('settling_amount', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('credit_score', models.FloatField(default=750, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('transactor', models.CharField(max_length=100, null=True)),
                ('expense', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('mpin', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dumy',
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user'),
        ),
        migrations.AddField(
            model_name='dummy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user'),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user'),
        ),
    ]
