# -*- coding: utf-8 -*-
"""Chatbot_Train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vgiCwbR4cW9Iel8_9J9mBL8cZW80RxRu
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib  # Add this import for saving models

# Load data from the CSV file
data = pd.read_csv("index.csv")

# Extract sentences and labels from the DataFrame
sentences = data['Sentence'].values
labels = data['Label'].values

# Convert sentences to TF-IDF features
tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(sentences)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

# Train an SVM classifier
classifier = SVC(kernel='linear')  # You can also try other kernels like 'rbf'
classifier.fit(X_train, y_train)

# Make predictions on the test set
predictions = classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: ", accuracy)

# Save the trained classifier and TF-IDF vectorizer
joblib.dump(classifier, 'svm_classifier_model.pkl')
joblib.dump(tfidf_vectorizer, 'tfidf_vectorizer.pkl')

